### ISSUE TITLE
Active Duty Maps navmesh fix?

### ISSUE THREAD

**Issue by BotAdmirer** [manicogaming/NavMeshes#1]
Is there a bug on active duty maps? CTs dont camp sites and split on B or A site, they rush alot. Terrorist also dont split when taking a site like on mirage they always rush A ramp, they should split A like 2 go A Palace and 3 go A Ramp.
Is there a way to fix this?

**Comment by manicogaming** [comment]
If CT BOTs are rushing to much maybe try to do some changes in your botprofile, the more Agression a BOT has the more likely it is for the BOT to rush, as for T BOTs I'm pretty sure they sometimes go palace.

**Comment by BotAdmirer** [comment]
How much aggression do you recommend? 45 or below?

**Comment by manicogaming** [comment]
I currently use 55.

**Comment by BotAdmirer** [comment]
Alright thank you for being active and replying quick. Love the BotImprover, last question - How do i make the bots use skins?

**Comment by manicogaming** [comment]
The plugin that gives BOTs skins is in this repo:
[https://github.com/manicogaming/CSGOBetterBots](url)

Only install the plugins from that repo if you know what you're doing!
