### ISSUE TITLE
One question of dust2

### ISSUE THREAD

**Issue by himenekocn** [manicogaming/NavMeshes#2]
Feedback: when I planted bomb on the box at BombsiteA of dust2, the bot will not defuse the bomb

**Comment by manicogaming** [comment]
This one?

![image](https://user-images.githubusercontent.com/8060047/128616280-03e2771e-e10b-4d58-8db0-9457db6821fc.png)

**Comment by himenekocn** [comment]
> This one?
> 
> ![image](https://user-images.githubusercontent.com/8060047/128616280-03e2771e-e10b-4d58-8db0-9457db6821fc.png)

yes
